/* ════════════════════════════════════════════════════════
   INVOKITPRO LICENCE SYSTEM
   Self-contained, server-free, tamper-evident.
   Keys are generated by the InvoKit Pro Licence Generator
   tool (separate file). Each key encodes the licensee's
   name, email, plan, issue date, and optional expiry.
   The HMAC checksum prevents key forgery or tampering.
   
   Distribution model:
   - You generate a unique key per buyer using the generator
   - The meta tag bkp-licence is set to "UNLICENSED" by default  
   - For a "clean" unlicensed file you distribute, the lock
     screen appears and the buyer enters their key
   - For a "pre-activated" file, set bkp-licence meta to the
     key and bkp-licensee to their name — app opens directly
   ════════════════════════════════════════════════════════ */

const BKP_SALT    = "InvoKitPro2024-xK9#mL2@vN7";
const BKP_UNREG_PREFIX = "UNREGISTERED-";
const BKP_ORG_KEY      = "invokitpro_lic_org";

const BKP_STORE_K = "bkp_lic_v2";

/* Decode a licence key → payload object or null */
function bkpDecode(key) {
  try {
    key = (key || '').trim().toUpperCase();
    if (!key.startsWith('BKP-')) return null;
    const parts = key.split('-');
    if (parts.length < 3) return null;
    const checksum  = parts[parts.length - 1];
    const b32part   = parts.slice(1, -1).join('-');
    const padding   = (8 - b32part.length % 8) % 8;
    const b32padded = b32part + '='.repeat(padding);
    // Base32 decode (A-Z 2-7)
    const B32 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
    let bits = 0, bitsLen = 0, bytes = [];
    for (const ch of b32padded) {
      if (ch === '=') break;
      const v = B32.indexOf(ch);
      if (v < 0) return null;
      bits = (bits << 5) | v; bitsLen += 5;
      if (bitsLen >= 8) { bitsLen -= 8; bytes.push((bits >> bitsLen) & 0xFF); }
    }
    let payloadJson;
    if (typeof TextDecoder !== 'undefined') {
      payloadJson = new TextDecoder().decode(new Uint8Array(bytes));
    } else {
      // Fallback for older iOS: manual UTF-8 decode
      payloadJson = bytes.map(b => String.fromCharCode(b)).join('');
    }
    const payload = JSON.parse(payloadJson);
    // Verify HMAC checksum via SubtleCrypto (async — handled in bkpVerify)
    return { payload, payloadJson, checksum };
  } catch(e) { return null; }
}

/* Pure-JS SHA-256 fallback for when SubtleCrypto is unavailable (Safari on file://) */
function _bkpSHA256(str) {
  function rr(w,b){return(w>>>b)|(w<<(32-b));}
  const K=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
    0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,
    0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,
    0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,
    0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,
    0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,
    0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,
    0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];
  const bytes=new TextEncoder().encode(str),len=bytes.length,blen=(len+9+63)&~63;
  const buf=new Uint8Array(blen);buf.set(bytes);buf[len]=0x80;
  const dv=new DataView(buf.buffer);dv.setUint32(blen-4,len*8,false);
  let [a,b,c,d,e,f,g,h]=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19];
  for(let i=0;i<blen;i+=64){
    const w=new Uint32Array(64);
    for(let j=0;j<16;j++)w[j]=dv.getUint32(i+j*4,false);
    for(let j=16;j<64;j++){const s0=(rr(w[j-15],7)^rr(w[j-15],18)^(w[j-15]>>>3)),s1=(rr(w[j-2],17)^rr(w[j-2],19)^(w[j-2]>>>10));w[j]=(w[j-16]+s0+w[j-7]+s1)>>>0;}
    let [A,B,C,D,E,F,G,H]=[a,b,c,d,e,f,g,h];
    for(let j=0;j<64;j++){
      const S1=(rr(E,6)^rr(E,11)^rr(E,25)),ch=((E&F)^(~E&G))>>>0,t1=(H+S1+ch+K[j]+w[j])>>>0;
      const S0=(rr(A,2)^rr(A,13)^rr(A,22)),maj=((A&B)^(A&C)^(B&C))>>>0,t2=(S0+maj)>>>0;
      H=G;G=F;F=E;E=(D+t1)>>>0;D=C;C=B;B=A;A=(t1+t2)>>>0;
    }
    a=(a+A)>>>0;b=(b+B)>>>0;c=(c+C)>>>0;d=(d+D)>>>0;e=(e+E)>>>0;f=(f+F)>>>0;g=(g+G)>>>0;h=(h+H)>>>0;
  }
  return[a,b,c,d,e,f,g,h].map(v=>v.toString(16).padStart(8,'0')).join('');
}

/* Async HMAC verify — returns payload if valid, null if forged/tampered.
   Uses SubtleCrypto where available, falls back to pure-JS SHA-256 for Safari on file:// */
async function bkpVerify(key) {
  try {
    const decoded = bkpDecode(key);
    if (!decoded) return null;
    const { payload, payloadJson, checksum } = decoded;
    let hashHex;
    if (typeof crypto !== 'undefined' && crypto.subtle && window.location.protocol === 'https:') {
      const data    = new TextEncoder().encode(payloadJson + BKP_SALT);
      const hashBuf = await crypto.subtle.digest('SHA-256', data);
      hashHex = Array.from(new Uint8Array(hashBuf))
        .map(b => b.toString(16).padStart(2,'0')).join('').toUpperCase();
    } else {
      hashHex = _bkpSHA256(payloadJson + BKP_SALT).toUpperCase();
    }
    if (hashHex.slice(0, 8) !== checksum) return null;
    if (payload.x) {
      const expiry  = new Date(payload.x);
      const now     = new Date();
      const daysLeft = Math.ceil((expiry - now) / (1000*60*60*24));
      if (expiry < now) {
        // Lifetime plans never truly expire even if x is set
        if (payload.p === 'lifetime') return payload;
        return { ...payload, _expired: true, _daysLeft: daysLeft };
      }
      return { ...payload, _daysLeft: daysLeft };
    }
    return payload;
  } catch(e) {
    console.warn('[InvoKit] Licence verify error:', e);
    return null;
  }
}

/* Boot — runs at app start. Fail-CLOSED: any error shows lock screen, never opens app.
   Key priority: embedded meta tag → localStorage → lock screen. */
async function bkpBoot() {
  try {
    // 1. Pre-activated file: key baked into meta tag by licence generator
    const metaEl  = document.querySelector('meta[name="bkp-licence"]');
    const metaKey = metaEl ? metaEl.getAttribute('content') : '';
    if (metaKey && metaKey !== 'UNLICENSED') {
      const payload = await bkpVerify(metaKey);
      if (payload) { bkpApplyLicence(payload); return true; }
    }
    // 2. Previously activated — check sync stores first, then IDB fallback
    const storedKey = bkpLoadStoredKey();
    if (storedKey) {
      const payload = await bkpVerify(storedKey);
      if (payload) { bkpApplyLicence(payload); return true; }
      try { localStorage.removeItem(BKP_STORE_K); } catch(e) {}
      try { sessionStorage.removeItem(BKP_STORE_K); } catch(e) {}
    }
    // 2b. IDB fallback — catches file moves and renames
    const idbKey = await new Promise(res => bkpLoadFromIDB(res));
    if (idbKey && idbKey !== storedKey) {
      const payload = await bkpVerify(idbKey);
      if (payload) { bkpSaveLicence(idbKey); bkpApplyLicence(payload); return true; }
    }
    // 3. No valid licence — show lock screen
    _bkpShowLock();
    return false;
  } catch(e) {
    // Fail-closed: any unexpected error shows lock screen, never lets app through
    console.warn('[InvoKit] Licence boot error:', e);
    _bkpShowLock();
    return false;
  }
}

function _bkpShowLock() {
  document.body.style.visibility = 'visible';
  const lock = document.getElementById('bkp-lock');
  if (lock) {
    lock.style.display = 'flex';
    setTimeout(() => document.getElementById('bkp-key-inp')?.focus(), 150);
  }
}

/* Persist licence to localStorage */
function bkpSaveLicence(key) {
  try { localStorage.setItem(BKP_STORE_K, key); } catch(e) {}
  try { sessionStorage.setItem(BKP_STORE_K, key); } catch(e) {}
  try {
    const req = indexedDB.open('invokitpro_lic', 1);
    req.onupgradeneeded = e => e.target.result.createObjectStore('lic');
    req.onsuccess = e => {
      const tx = e.target.result.transaction('lic', 'readwrite');
      tx.objectStore('lic').put(key, 'key');
    };
  } catch(e) {}
  try {
    const exp = new Date(Date.now() + 1000*60*60*24*3650).toUTCString();
    document.cookie = `${BKP_STORE_K}=${encodeURIComponent(key)};expires=${exp};path=/;SameSite=Lax`;
  } catch(e) {}
}
function bkpLoadStoredKey() {
  try { const k = localStorage.getItem(BKP_STORE_K); if (k) return k; } catch(e) {}
  try { const k = sessionStorage.getItem(BKP_STORE_K); if (k) return k; } catch(e) {}
  try {
    const m = document.cookie.match(new RegExp('(?:^|;\\s*)' + BKP_STORE_K + '=([^;]+)'));
    if (m) return decodeURIComponent(m[1]);
  } catch(e) {}
  return null;
}
function bkpLoadFromIDB(cb) {
  try {
    const req = indexedDB.open('invokitpro_lic', 1);
    req.onupgradeneeded = e => e.target.result.createObjectStore('lic');
    req.onsuccess = e => {
      const tx = e.target.result.transaction('lic', 'readonly');
      const get = tx.objectStore('lic').get('key');
      get.onsuccess = () => cb(get.result || null);
      get.onerror   = () => cb(null);
    };
    req.onerror = () => cb(null);
  } catch(e) { cb(null); }
}

/* Apply a verified licence to the UI */
/* ── Expired licence screen (Annual plan only) ── */
function _bkpShowExpired(payload) {
  // Remove any existing expired overlay
  const existing = document.getElementById('bkp-expired-overlay');
  if (existing) existing.remove();

  const overlay = document.createElement('div');
  overlay.id = 'bkp-expired-overlay';
  overlay.style.cssText = 'position:fixed;inset:0;z-index:9998;background:rgba(15,36,71,.96);display:flex;align-items:center;justify-content:center;padding:24px;font-family:Segoe UI,system-ui,sans-serif;backdrop-filter:blur(4px);animation:sfade .25s ease;';
  overlay.innerHTML = `
    <div style="background:#fff;border-radius:16px;padding:36px 40px;max-width:400px;width:100%;text-align:center;box-shadow:0 24px 64px rgba(0,0,0,.4);">
      <div style="width:56px;height:56px;background:#fef2f2;border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 auto 16px;">
        <svg viewBox="0 0 24 24" width="26" height="26" fill="none" stroke="#dc2626" stroke-width="2"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
      </div>
      <div style="font-family:Georgia,serif;font-size:1.25rem;font-weight:700;margin-bottom:8px;color:#111;">Annual Licence Expired</div>
      <div style="font-size:.83rem;color:#6b7280;line-height:1.65;margin-bottom:24px;">
        Your InvoKit Pro Annual licence for <strong>${payload.n||'your account'}</strong> expired on <strong>${payload.x||'—'}</strong>.<br><br>
        Renew to continue using InvoKit Pro and keep access to all your data.
      </div>
      <a href="https://wa.me/447310211892?text=Hi%2C%20I%20need%20to%20renew%20my%20InvoKit%20Pro%20Annual%20licence.%20Name%3A%20${encodeURIComponent(payload.n||'')}%20Email%3A%20${encodeURIComponent(payload.e||'')}"
         target="_blank"
         style="display:block;padding:12px;background:#1a3a6b;color:#fff;border-radius:8px;text-decoration:none;font-weight:700;font-size:.88rem;margin-bottom:10px;">
        🔄 Renew My Licence
      </a>
      <button onclick="document.getElementById('bkp-expired-overlay').remove()"
        style="width:100%;padding:10px;background:none;border:1.5px solid #e5e7eb;border-radius:8px;color:#6b7280;font-size:.82rem;cursor:pointer;font-family:inherit;">
        Continue in Read-Only Mode
      </button>
      <div style="font-size:.7rem;color:#ccc;margin-top:14px;">Your data is safe and has not been deleted.</div>
    </div>`;
  document.body.appendChild(overlay);
}

function bkpApplyLicence(payload) {
  // Hide lock screen and reveal app
  const lock = document.getElementById('bkp-lock');
  if (lock) lock.style.display = 'none';
  document.body.style.visibility = 'visible';
  // Show badge
  const badge     = document.getElementById('bkp-badge');
  const badgeName = document.getElementById('bkp-badge-name');
  if (badge && badgeName) {
    badgeName.textContent = payload.n;
    badge.style.display   = 'flex';
    const planDisplay = payload.p === 'annual' ? 'Annual (£25/yr)' : payload.p === 'lifetime' ? 'Lifetime (£60)' : payload.p;
    badge.title           = `Licensed to: ${payload.n}${payload.o ? ' — ' + payload.o : ''}\n${payload.e}\nPlan: ${planDisplay}\nIssued: ${payload.d}`;
  }
  // Store in global for other parts of app
  window._bkpLicence = payload;
  // Lock business name to licence org (supports first-time registration pool keys)
  if (payload.o) {
    const override = _getStoredOrgOverride();
    if (_isUnregisteredOrg(payload.o) && override) {
      _lockBusinessName(override);
    } else if (_isUnregisteredOrg(payload.o) && !override) {
      // Pool key: allow onboarding to set business name once, then lock it.
    } else {
      _lockBusinessName(payload.o);
    }
  }

  // Expiry enforcement
  if (payload._expired) {
    // Annual plan expired — block the app with renewal screen
    setTimeout(() => _bkpShowExpired(payload), 500);
  } else if (payload._daysLeft !== undefined && payload._daysLeft <= 7 && payload.p === 'annual') {
    // Annual plan expiring within 7 days — soft warning
    setTimeout(() => toast(`Your Annual licence expires in ${payload._daysLeft} day${payload._daysLeft===1?'':'s'}. Please renew soon.`,'er'), 2500);
  }
  // Show iOS install hint if on iOS Safari and not already installed
  setTimeout(_showIOSInstallHint, 3000);
}

function _lockBusinessName(orgName) {
  // Write org name into settings
  const stored = JSON.parse(localStorage.getItem('invokitpro_settings') || '{}');
  if (!stored.name) {
    // Only auto-fill if not already set
    stored.name = orgName;
    localStorage.setItem('invokitpro_settings', JSON.stringify(stored));
    const nameInput = document.getElementById('s-name');
    if (nameInput) nameInput.value = orgName;
  }
  // Lock the field visually
  const nameInput = document.getElementById('s-name');
  if (nameInput) {
    nameInput.readOnly = true;
    nameInput.style.cssText += ';background:var(--sur2);cursor:not-allowed;padding-right:32px;';
    nameInput.title = 'Business name is locked to your licence';
    nameInput.removeAttribute('oninput');
    nameInput.addEventListener('focus', () => toast('Business name is locked to your licence. Contact support to update.', 'er'));
    // Add padlock icon next to field
    const fg = nameInput.closest('.fg');
    if (fg && !fg.querySelector('.lock-icon')) {
      const lbl = fg.querySelector('label');
      if (lbl) lbl.innerHTML = 'Business Name <span class="lock-icon" title="Locked to licence" style="font-size:.75rem;color:var(--muted);">🔒</span>';
      const wrap = document.createElement('div');
      wrap.style.cssText = 'position:relative;';
      nameInput.parentNode.insertBefore(wrap, nameInput);
      wrap.appendChild(nameInput);
    }
  }
  // Save locked state so it persists across page loads
  localStorage.setItem('invokitpro_name_locked', '1');
  localStorage.setItem('invokitpro_name_locked_val', orgName);
}

function _restoreNameLock() {
  // Called on app load — re-apply lock if previously locked
  const locked = localStorage.getItem('invokitpro_name_locked');
  const val    = localStorage.getItem('invokitpro_name_locked_val');
  if (locked && val) _lockBusinessName(val);
}


function _isUnregisteredOrg(org) {
  return typeof org === 'string' && org.toUpperCase().startsWith(BKP_UNREG_PREFIX);
}
function _getStoredOrgOverride() {
  try { return (localStorage.getItem(BKP_ORG_KEY) || '').trim(); } catch(e) { return ''; }
}
function _setOrgOverride(org) {
  try { localStorage.setItem(BKP_ORG_KEY, org); } catch(e) {}
}
function _clearOrgOverride() {
  try { localStorage.removeItem(BKP_ORG_KEY); } catch(e) {}
}

function _enforceFirstTimeOrgRegistrationFromOnboarding() {
  const lic = window._bkpLicence;
  if (!lic || !lic.o) return true;
  if (_isUnregisteredOrg(lic.o) && !_getStoredOrgOverride()) {
    const name = (document.getElementById('ob-bname')?.value || '').trim();
    if (!name) {
      if (typeof toast === 'function') toast('Please enter your Business Name to complete activation.', 'er');
      document.getElementById('ob-bname')?.focus();
      return false;
    }
    _setOrgOverride(name);
    _lockBusinessName(name);
  }
  return true;
}



/* Activate flow — called when user submits key in lock screen */
async function bkpActivate() {
  const inp = document.getElementById('bkp-key-inp');
  const err = document.getElementById('bkp-err');
  if (!inp) return;
  const key = inp.value.trim();
  err.textContent = '';
  inp.classList.remove('er');
  if (!key) { err.textContent = 'Please enter your licence key.'; inp.classList.add('er'); return; }
  const btn = document.querySelector('.bkp-lock-btn');
  if (btn) { btn.textContent = 'Verifying…'; btn.disabled = true; }
  const payload = await bkpVerify(key);
  if (btn) { btn.textContent = 'Activate InvoKit Pro'; btn.disabled = false; }
  if (!payload) {
    err.textContent = 'Invalid or tampered licence key. Please check and try again.';
    inp.classList.add('er');
    inp.select();
    return;
  }
  bkpSaveLicence(key);
  bkpApplyLicence(payload);
  toast(`Welcome, ${payload.n}! InvoKit Pro activated ✓`, 'ok');
  // App is already fully initialised — bkpApplyLicence just hides the lock screen.
  // If first time (no onboarding done), show the onboarding wizard.
  if (!localStorage.getItem('ik_onboarded') || !_settings.name || !_settings.cur) {
    setTimeout(() => openOnboarding(), 400);
  }
}
window.bkpActivate = bkpActivate;

init();
